#! /usr/bin/env bash

session=$(find ~ ~/benni-projects/ ~/work-projects/ -mindepth 1 -maxdepth 2 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -d -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
 
# This script will find all directories in the home directory,  ~/benni-projects/ , and  ~/work-projects/  and pipe them into  fzf . When you select a directory, it will create a new tmux session with the name of the directory and switch to it. 
# You can also use  fzf  to select a tmux session to switch to. 
 # Path: tmux-sessionizer
