# name|ghostty theme|tmux flavor|neovim flavor|VS Code theme|appearance|wallpaper
latte|Catppuccin Latte|latte|latte|Catppuccin Latte|light|$HOME/.config/theme-switcher/wallpapers/latte.jpg
frappe|Catppuccin Frappe|frappe|frappe|Catppuccin Frappe|dark|$HOME/.config/theme-switcher/wallpapers/frappe.jpg
macchiato|Catppuccin Macchiato|macchiato|macchiato|Catppuccin Macchiato|dark|$HOME/.config/theme-switcher/wallpapers/macchiato.jpg
mocha|Catppuccin Mocha|mocha|mocha|Catppuccin Mocha|dark|$HOME/.config/theme-switcher/wallpapers/mocha.jpg
tokyonight|TokyoNight Night|mocha|tokyonight|Tokyo Night|dark|$HOME/.config/theme-switcher/wallpapers/tokyonight.jpg
night-owl|Night Owl|mocha|night-owl|Night Owl|dark|$HOME/.config/theme-switcher/wallpapers/night-owl.jpg
